# EnchantmentSlots by @PQguanfang
#
# READ THE WIKI: simple.superiormc.cn/

# Settings
settings:
  debug: false
  add-lore:
    # Does not support other packed-based item, enchants plugins.
    # Like EcoEnchants, EcoItems.
    # They will always put their lore at first location and EnchantmentSlots can do nothing about it.
    at-first-or-last: false
    # Do not change this option when server started!
    # Only change this if your server has stopped!
    # Do not use common symbols!
    # Plugin will try deletes all lore that similar to below!
    # If you want to use empty line, use '&7   ' instead!
    # - '&7   ' is right, the more space you have, the more safe it is.
    # - '' is wrong. It will make item lose all empty line you set by other plugins!
    display-value:
      - "&#ff3300Enchantment Slots: {enchant_amount}/{slot_amount}"
      - "{enchants}"
      - "{empty_slots}"
    # Do not change this option when server started!
    # Only change this if your server has stopped!
    placeholder:
      enchants:
        format: '&6  {enchant_name}'
      empty-slots:
        format: '&7  --- Empty Slot ---'
    trigger:
      Packet:
        enabled: false
        auto-check: false
        whitelist-items:
          - wooden_pickaxe
          - stone_pickaxe
          - iron_pickaxe
          - golden_pickaxe
          - diamond_pickaxe
          - netherite_pickaxe
          - wooden_hoe
          - stone_hoe
          - iron_hoe
          - golden_hoe
          - diamond_hoe
          - netherite_hoe
          - wooden_axe
          - stone_axe
          - iron_axe
          - golden_axe
          - diamond_axe
          - wooden_shovel
          - stone_shovel
          - iron_shovel
          - golden_shovel
          - diamond_shovel
          - netherite_shovel
          - wooden_sword
          - stone_sword
          - iron_sword
          - golden_sword
          - diamond_sword
          - netherite_sword
          - fishing_rod
          - elytra
          - bow
          - crossbow
          - carrot_on_a_stick
          - shield
          - turtle_helmet
          - leather_helmet
          - chainmail_helmet
          - iron_helmet
          - golden_helmet
          - diamond_helmet
          - netherite_helmet
          - leather_chestplate
          - chainmail_chestplate
          - iron_chestplate
          - golden_chestplate
          - diamond_chestplate
          - netherite_chestplate
          - leather_leggings
          - chainmail_leggings
          - iron_leggings
          - golden_leggings
          - diamond_leggings
          - netherite_leggings
          - leather_boots
          - chainmail_boots
          - iron_boots
          - golden_boots
          - diamond_boots
          - netherite_boots
      EnchantItemEvent:
        enabled: true
      InventoryClickEvent:
        enabled: true
    black-creative-mode: false
  default-slots:
    default: 5
    vip: 10
  #default-slots-by-item:
  #  diamond_sword:
  #    default: 20
  #    vip: 30
  #  # You can type third plugin item ID here.
  #  # For now, EnchantmentSlots support:
  #  # MMOItems, EcoItems, EcoArmor, MythicMobs, NeigeItems, ItemsAdder, Oraxen.
  #  superior_sword:
  #    default: 100
  #    vip: 200
  # Only work for extra slot items.
  # Remove this section if you don't want this feature.
  max-slots:
    default: 10
    vip: 15
  # max-slots-by-item
  # Similar to default-slots-by-item, remove the section to not use this feature.
  slots-conditions:
    vip:
      - 'permission: group.vip'
  close-inventory-if-reached-limit: true
  remove-illegal-extra-enchant: true
  black-creative-mode-player: true

add-slot-items:
  A:
    material: PAPER
    name: '&dExtra Enchantment Slot &7(+1)'
    lore:
      - '&fDrag this item into your item to use!'
    add-slots: 1
  B:
    material: PAPER
    custom-model-data: 5
    name: '&dExtra Enchantment Slot &7(+5)'
    lore:
      - '&fDrag this item into your item to use!'
    add-slots: 5

# Enchant Name
enchant-name:
  # Default providing vanilla enchantments here.
  # For third enchantment plugins:
  # Plugin will auto get enchantment display name that provided by EcoEnchants and ExcellentEnchants
  # If you are not using the 2 plugins, please using "Enchantment Key: Enchantment Display Name" format
  # Like:
  # an_other_enchantment: 'This is just an example here!'
  protection: 'Protection'
  fire_protection: 'Fire Protection'
  feather_falling: 'Feather Falling'
  blast_protection: 'Blast Protection'
  projectile_protection: 'Projectile Protection'
  respiration: 'Respiration'
  aqua_affinity: 'Aqua Affinity'
  thorns: 'Thorns'
  depth_strider: 'Depth Strider'
  frost_walker: 'Frost Walker'
  binding_curse: 'Binding Curse'
  sharpness: 'Sharpness'
  smite: 'Smite'
  bane_of_arthropods: 'Bane of Arthropods'
  knockback: 'Knockback'
  fire_aspect: 'Fire Aspect'
  looting: 'Looting'
  sweeping: 'Sweeping'
  efficiency: 'Efficiency'
  silk_touch: 'Silk Touch'
  unbreaking: 'Unbreaking'
  fortune: 'Fortune'
  power: 'Power'
  punch: 'Punch'
  flame: 'Flame'
  infinity: 'Infinity'
  luck_of_the_sea: 'Luck of the Sea'
  lure: 'Lure'
  loyalty: 'Loyalty'
  impaling: 'Impaling'
  riptide: 'Riptide'
  channeling: 'Channeling'
  multishot: 'Multishot'
  quick_charge: 'Quick Charge'
  piercing: 'Piercing'
  mending: 'Mending'
  vanishing_curse: 'Vanishing Curse'
  soul_speed: 'Soul Speed'

# Messages
messages:
  plugin-reloaded: "&#98FB98[EnchantmentSlots] &fPlugin reloaded!"
  help-main: |
    &#98FB98&lEnchantmentSlots &7Made by @PQguanfang
    &f/es help &7- View help.
  help-main-admin: |
    &#98FB98&lEnchantmentSlots &7Made by @PQguanfang
    &f/es help &7- View help.
    &f/es reload &7- Reload the plugin.
    &f/es setslots <amount> &7- Set enchantment slot to specified amount.
    &f/es giveslots <amount> &7- Add enchantment slots specified amount.
    &f/es giveslots <itemID> <player> &7- Give extra slot item to specified player.
  help-main-console: |
    &#98FB98&lEnchantmentSlots &7Made by @PQguanfang
    &f/es help &7- View help.
    &f/es reload &7- Reload the plugin.
    &f/es giveslots <itemID> <player> &7- Give extra slot item to specified player.
  give-extra-slot-item: "&#98FB98[EnchantmentSlots] &aGave %player% extra slot item %item% x%amount%"
  success-add: "&#98FB98[EnchantmentSlots] &aAdd %amount% extra main hand item enchantment slot!"
  success-set: "&#98FB98[EnchantmentSlots] &aSet main hand item enchantment slot to %amount%!"
  slots-limit-reached: "&#98FB98[EnchantmentSlots] &cYour item has reached its enchantment limits!"
  max-slots-reached: "&#98FB98[EnchantmentSlots] &cYour item can not have more enchantment slots!"
  error-args: "&#98FB98[EnchantmentSlots] &cWrong command usage, if you need help, use /es help!"
  error-miss-permission: "&#98FB98[EnchantmentSlots] &cYou don't have permission to use this command!"
  error-in-game: "&#98FB98[EnchantmentSlots] &cYou have to use this command in game!"
  error-no-item: "&#98FB98[EnchantmentSlots] &cCan not get item in your main hand!"
  player-not-found: "&#98FB98[EnchantmentSlots] &cWe can't find player %player%!"